on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Send files to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: '.'
          remote:  '/var/projects/data-server'
          host: ${{ secrets.SFTP_IP }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_IP }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            cd /var/projects/data-server
            npm install
            npm run build
            pm2 stop data-server; pm2 delete data-server; pm2 start build/index.js --name data-server
